# REMEMBER: update recipe/variants/*.yaml if this gets updated
c_compiler:
  - gcc
  - zig
  - vs2022
c_compiler_version:
  - "14"
  - "0.15.2"
  - "*"
c_stdlib:
  - m2w64-sysroot
  - zig
  - vs
c_stdlib_version:
  - "12"
  - "0.15.2"
  - "*"

zip_keys:
  -
    - c_compiler
    - c_compiler_version
    - c_stdlib
    - c_stdlib_version
