context:
  version: "24.7.1"
  build_number: 4
  arch_suffix : ${{ target_platform | split ("-") | last }}

recipe:
  name: conda-launchers
  version: ${{ version }}

source:
  - path: ../src
  - url: https://raw.githubusercontent.com/python/cpython/3.7/PC/launcher.c
    sha256: a3167e5908cefa942f63e0de5c6ec7a929e8ca82a382537ab8292e5aaa82ca2e
    file_name: launcher.c.orig
    # BUG in rattler-build, need to patch manually
    # See https://github.com/prefix-dev/rattler-build/issues/2467
    # patches:
    #   - ../src/cpython-launcher-c-mods-for-setuptools.3.7.patch
  - url: https://raw.githubusercontent.com/python/cpython/3.7/LICENSE
    sha256: 96e4f59524cde5af4a2ea837ef5e52b65e51f1f999825fd8a9ec3b444cb82aea
    file_name: cpython-LICENSE

build:
  number: ${{ build_number }}
  skip:
    - unix

outputs:
  - package:
      name: conda-launchers

    build:
      string: ${{ hash }}_${{ c_compiler }}_${{ build_number }}
      script:
        file: ${{ 'build-zig.bat' if c_compiler == 'zig' else 'build-sh.bat' }}
      variant:
        down_prioritize_variant: ${{ 2 if c_compiler == 'zig' else 1 if c_compiler == 'vs' else 0 }}

    requirements:
      ignore_run_exports:
        from_package:
          - ${{ compiler("c") }}
          - ${{ stdlib("c") }}
      build:
        - if: c_compiler == 'zig'
          then:
            - zig
          else:
            - ${{ compiler("c") }}
            - ${{ stdlib("c") }}
        - m2-patch

    tests:
      - package_contents:
          files:
            # cli
            - Scripts/cli-${{ arch_suffix }}.exe
            - Scripts/cli-${{ arch_suffix }}-script.py
            # gui
            - Scripts/gui-${{ arch_suffix }}.exe
            - Scripts/gui-${{ arch_suffix }}-script.pyw
      - script:
          - set PYLAUNCH_DEBUG=1
          - cli-${{ arch_suffix }}
          - if not exist cli-${{ arch_suffix }}-output.txt exit 1
        requirements:
          run:
            - python

about:
  homepage: https://github.com/conda/conda-launchers
  summary: Conda's Windows launchers for Python entry points
  description: |
    Windows launchers for Python entry points used in the conda ecosystem

    In order to launch Python entrypoints properly on Windows, a corresponding
    executable is used to proxy the call because shebangs do not work on Windows.
    This is achieved by the launchers (or called shims).
  license: Python-2.0 AND BSD-3-Clause
  license_file:
    - cpython-LICENSE
    - LICENSE
  repository: https://github.com/conda/conda-launchers

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
