[workspace]
name = "conda-launchers"
version = "0.1.0"
description = "Conda launchers for Windows"
channels = ["conda-forge"]
platforms = ["win-64"]
license = "BSD-3-Clause"

[dependencies]
# >=0.69 for conditional noarch support (prefix-dev/rattler-build#2626)
rattler-build = ">=0.69"

[feature.extract.dependencies]
conda-package-handling = "*"

[environments]
extract = ["extract"]
