[workspace]
name = "conda-launchers"
version = "0.1.0"
description = "Conda launchers for Windows"
channels = ["conda-forge"]
platforms = ["win-64"]
license = "BSD-3-Clause"

[dependencies]
rattler-build = "*"

[feature.extract.dependencies]
conda-package-handling = "*"

[environments]
extract = ["extract"]
