name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build recipe with ${{ matrix.compiler }} for ${{ matrix.target-platform }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # GCC stack on Windows is only available for win-64
          - compiler: gcc
            target-platform: win-64
            runs-on: windows-latest

          # conda-forge maintain doesn't really maintain a win-32 stack for MSVC anymore
          - compiler: vs
            target-platform: win-64
            runs-on: windows-latest
          - compiler: vs
            target-platform: win-arm64
            runs-on: windows-11-arm

          - compiler: zig
            target-platform: win-32
            runs-on: windows-latest
          - compiler: zig
            target-platform: win-64
            runs-on: windows-latest
          - compiler: zig
            target-platform: win-arm64
            runs-on: windows-11-arm
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          cache: true

      - name: Pixi info
        shell: pwsh
        run: |
          pixi info
          pixi list

      - name: Run Build
        shell: pwsh
        run: |
          pixi run rattler-build build `
          --recipe recipe `
          --ignore-recipe-variants `
          --variant-config recipe\variants\${{ matrix.compiler }}.yaml `
          --target-platform ${{ matrix.target-platform }} `
          --log-style plain `
          --skip-existing all `
          --channel conda-forge `
          --extra-meta flow_run_id="github_$GITHUB_RUN_ID" `
          --extra-meta remote_url="https://github.com/$GITHUB_REPOSITORY" `
          --extra-meta sha="$GITHUB_SHA"

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: conda-launchers-builds-${{ matrix.compiler }}-${{ matrix.target-platform }}
          path: |
            ./output/${{ matrix.target-platform }}/conda-launchers*.conda

  upload-channel:
    name: Upload to canary channel
    needs: [build]
    runs-on: windows-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release'
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Download All Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: output
          pattern: conda-launchers-builds-*
          merge-multiple: true

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          cache: true

      - name: Pixi info
        shell: pwsh
        run: |
          pixi info
          pixi list

      - name: List artifacts
        shell: pwsh
        run: |
          dir output

      - name: Upload to Anaconda
        env:
          # rattler-build upload knows how to take auth from these env vars
          ANACONDA_OWNER: conda-canary
          ANACONDA_CHANNEL: conda-launchers_dev
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_ORG_CONDA_CANARY_TOKEN }}
        shell: pwsh
        run: |
          pixi run rattler-build upload anaconda --log-style plain ./output/conda-launchers*.conda
